export { Add20Regular } from "@fluentui/react-icons/headless/svg/add";
export { AppsListDetail20Regular, AppsListDetail24Regular } from "@fluentui/react-icons/headless/svg/apps-list-detail";
export { ArrowLeft20Regular } from "@fluentui/react-icons/headless/svg/arrow-left";
export { ArrowRight20Regular } from "@fluentui/react-icons/headless/svg/arrow-right";
export { ArrowUpRight20Regular, ArrowUpRight24Regular } from "@fluentui/react-icons/headless/svg/arrow-up-right";
export { BookOpen24Regular } from "@fluentui/react-icons/headless/svg/book-open";
export { Checkmark16Regular } from "@fluentui/react-icons/headless/svg/checkmark";
export { ChevronLeft24Regular } from "@fluentui/react-icons/headless/svg/chevron-left";
export { ChevronRight20Regular, ChevronRight24Regular } from "@fluentui/react-icons/headless/svg/chevron-right";
export { Dismiss20Regular, Dismiss24Regular } from "@fluentui/react-icons/headless/svg/dismiss";
export { DocumentBulletList24Regular } from "@fluentui/react-icons/headless/svg/document-bullet-list";
export { Eye24Regular } from "@fluentui/react-icons/headless/svg/eye";
export { Flash24Regular } from "@fluentui/react-icons/headless/svg/flash";
export { Link16Regular } from "@fluentui/react-icons/headless/svg/link";
export { Megaphone24Regular } from "@fluentui/react-icons/headless/svg/megaphone";
export { Navigation24Regular } from "@fluentui/react-icons/headless/svg/navigation";
export { Open20Regular, Open24Regular } from "@fluentui/react-icons/headless/svg/open";
export { Search20Regular } from "@fluentui/react-icons/headless/svg/search";
export { Shield24Regular } from "@fluentui/react-icons/headless/svg/shield";
export { ShieldCheckmark24Filled } from "@fluentui/react-icons/headless/svg/shield-checkmark";
export { Sparkle12Filled } from "@fluentui/react-icons/headless/svg/sparkle";
export { Timeline24Regular } from "@fluentui/react-icons/headless/svg/timeline";
export { Timer24Regular } from "@fluentui/react-icons/headless/svg/timer";
export { ZoomIn24Regular } from "@fluentui/react-icons/headless/svg/zoom-in";
